### ISSUE TITLE
relfex grid v2

### ISSUE THREAD

**Issue by leejordan** [idenisovs/react-reflex-grid#1]
Hey just a heads up but if you wanted to update to version 2 of reflex grid some of the class names have changed but it's otherwise much more robust than 1.5.0 that you are using.

- http://reflexgrid.com
- https://github.com/leejordan/reflex
- http://lendmeyourear.net/reflex-grid-version-2.html

**Comment by idenisovs** [comment]
@leejordan Hi! Thank you for note and for your great job! I have updated reflex-grid version just now, and also, some updates of react-reflex-grid is coming!
